name: Integração continua

on:
  push:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16.1
        cache: 'npm'
    - run: npm install
    - run: npm run test
      continue-on-error: true
    - run: npm run test:healthcheck
    - run: npm run test:contract
    - run: npm run test:functional
